import type { DeviceDefinition } from "./types";

export const androidDevices: DeviceDefinition[] = [
  {
    id: "pixel-9-pro",
    name: "Pixel 9 Pro",
    brand: "android",
    category: "phone",
    store: "play-store",
    screenWidth: 1344,
    screenHeight: 2992,
    screenX: 40,
    screenY: 40,
    frameWidth: 1424,
    frameHeight: 3072,
    framePath: "/devices/frames/pixel-9-pro.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Obsidian", "Porcelain", "Hazel", "Rose Quartz"],
  },
  {
    id: "galaxy-s25",
    name: "Samsung Galaxy S25",
    brand: "android",
    category: "phone",
    store: "play-store",
    screenWidth: 1440,
    screenHeight: 3120,
    screenX: 40,
    screenY: 40,
    frameWidth: 1520,
    frameHeight: 3200,
    framePath: "/devices/frames/galaxy-s25.svg",
    frameFormat: "svg",
    year: 2025,
    colorVariants: ["Phantom Black", "Cream", "Icy Blue", "Mint", "Navy"],
  },
  {
    id: "android-phone-generic",
    name: "Android Phone",
    brand: "android",
    category: "phone",
    store: "play-store",
    screenWidth: 1080,
    screenHeight: 1920,
    screenX: 40,
    screenY: 40,
    frameWidth: 1160,
    frameHeight: 2000,
    framePath: "/devices/frames/android-phone-generic.svg",
    frameFormat: "svg",
    year: 2024,
  },
  {
    id: "android-tablet-10",
    name: 'Android Tablet 10"',
    brand: "android",
    category: "tablet",
    store: "play-store",
    screenWidth: 1200,
    screenHeight: 1920,
    screenX: 50,
    screenY: 50,
    frameWidth: 1300,
    frameHeight: 2020,
    framePath: "/devices/frames/android-tablet-10.svg",
    frameFormat: "svg",
    year: 2024,
  },
];
