import type { DeviceDefinition } from "./types";

export const appleDevices: DeviceDefinition[] = [
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "apple",
    category: "phone",
    store: "app-store",
    screenWidth: 1320,
    screenHeight: 2868,
    screenX: 40,
    screenY: 40,
    frameWidth: 1400,
    frameHeight: 2948,
    framePath: "/devices/frames/iphone-16-pro-max.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Black Titanium", "White Titanium", "Natural Titanium", "Desert Titanium"],
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "apple",
    category: "phone",
    store: "app-store",
    screenWidth: 1206,
    screenHeight: 2622,
    screenX: 40,
    screenY: 40,
    frameWidth: 1286,
    frameHeight: 2702,
    framePath: "/devices/frames/iphone-16-pro.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Black Titanium", "White Titanium", "Natural Titanium", "Desert Titanium"],
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    brand: "apple",
    category: "phone",
    store: "app-store",
    screenWidth: 1179,
    screenHeight: 2556,
    screenX: 40,
    screenY: 40,
    frameWidth: 1259,
    frameHeight: 2636,
    framePath: "/devices/frames/iphone-16.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Black", "White", "Pink", "Teal", "Ultramarine"],
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    brand: "apple",
    category: "phone",
    store: "app-store",
    screenWidth: 1179,
    screenHeight: 2556,
    screenX: 40,
    screenY: 40,
    frameWidth: 1259,
    frameHeight: 2636,
    framePath: "/devices/frames/iphone-15.svg",
    frameFormat: "svg",
    year: 2023,
    colorVariants: ["Black", "Blue", "Green", "Yellow", "Pink"],
  },
  {
    id: "iphone-se-3",
    name: "iPhone SE (3rd gen)",
    brand: "apple",
    category: "phone",
    store: "app-store",
    screenWidth: 750,
    screenHeight: 1334,
    screenX: 40,
    screenY: 40,
    frameWidth: 830,
    frameHeight: 1414,
    framePath: "/devices/frames/iphone-se-3.svg",
    frameFormat: "svg",
    year: 2022,
    colorVariants: ["Midnight", "Starlight", "Product Red"],
  },
  {
    id: "ipad-pro-13",
    name: 'iPad Pro 13"',
    brand: "apple",
    category: "tablet",
    store: "app-store",
    screenWidth: 2064,
    screenHeight: 2752,
    screenX: 50,
    screenY: 50,
    frameWidth: 2164,
    frameHeight: 2852,
    framePath: "/devices/frames/ipad-pro-13.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Space Black", "Silver"],
  },
  {
    id: "ipad-pro-11",
    name: 'iPad Pro 11"',
    brand: "apple",
    category: "tablet",
    store: "app-store",
    screenWidth: 1668,
    screenHeight: 2388,
    screenX: 50,
    screenY: 50,
    frameWidth: 1768,
    frameHeight: 2488,
    framePath: "/devices/frames/ipad-pro-11.svg",
    frameFormat: "svg",
    year: 2024,
    colorVariants: ["Space Black", "Silver"],
  },
];
